framework:
    notifier:
        chatter_transports:
            discord: '%env(DISCORD_DSN)%'
        #    telegram: '%env(TELEGRAM_DSN)%'
        #texter_transports:
        #    twilio: '%env(TWILIO_DSN)%'
        #    nexmo: '%env(NEXMO_DSN)%'
        channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
            urgent: ['email', 'chat/discord']
            high: ['email', 'chat/discord']
            medium: ['email', 'chat/discord']
            low: ['email', 'chat/discord']
        admin_recipients:
            - { email: "%env(string:default:default_admin_email:ADMIN_EMAIL)%" }
